name: Pre-Release

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  create-pre-release:
    name: Create Pre-Release
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Retrieve Version
        id: version
        run: echo "value=$(node -pe 'require("./package.json").version')-dev.${{ github.run_number }}" >> $GITHUB_OUTPUT
      - name: Trigger Workflow
        run: |
          set -e
          curl -X POST https://api.github.com/repos/Chillibean/accounts-api-client-sdk/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.API_SPEC_PAT_TOKEN }} \
          --data '{"event_type": "trigger-release", "client_payload": { "version": "3.0.0" }}' \
          --fail
    outputs:
      version: ${{ steps.version.outputs.value }}
